// <auto-generated />
using System;
using LeadManagementPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadManagementPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417042340_AddBusinessAccountProductPricing")]
    partial class AddBusinessAccountProductPricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeadManagementPortal.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SalesGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SalesOrgId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SalesGroupId");

                    b.HasIndex("SalesOrgId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LeadManagementPortal.Models.BusinessAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey");

                    b.HasIndex("Name");

                    b.ToTable("BusinessAccounts");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.BusinessAccountProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAccountId", "EffectiveStartDate", "EffectiveEndDate");

                    b.HasIndex("BusinessAccountId", "ProductName", "IsActive");

                    b.ToTable("BusinessAccountProductPrices");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BeneficiaryId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedById");

                    b.ToTable("CommissionAdjustments");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProductNameFilter")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAccountId", "IsActive", "EffectiveStartDate", "EffectiveEndDate");

                    b.ToTable("CommissionAgreements");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAgreementRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BasisRecipientId")
                        .HasColumnType("int");

                    b.Property<string>("BeneficiaryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CalculationType")
                        .HasColumnType("int");

                    b.Property<int>("CommissionAgreementId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("RateOrAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasisRecipientId");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("CommissionAgreementId");

                    b.ToTable("CommissionAgreementRecipients");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionDeal", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("BaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CalculationBasis")
                        .HasColumnType("int");

                    b.Property<int>("DealType")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ApplicationUserId");

                    b.ToTable("CommissionDeals");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BeneficiaryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CalculationNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChainDepth")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DealSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SaleRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("SaleRecordId");

                    b.HasIndex("SaleRecordId", "BeneficiaryId")
                        .IsUnique();

                    b.ToTable("CommissionLedgers");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BeneficiaryId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CalculationDetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalculationType")
                        .HasColumnType("int");

                    b.Property<int>("CommissionAgreementId")
                        .HasColumnType("int");

                    b.Property<int?>("CommissionAgreementRecipientId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EarnedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SaleEventId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("CommissionAgreementId");

                    b.HasIndex("CommissionAgreementRecipientId");

                    b.HasIndex("EarnedAtUtc");

                    b.HasIndex("SaleEventId");

                    b.ToTable("CommissionLedgerEntries");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionLink", b =>
                {
                    b.Property<string>("DownlineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SponsorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DownlineId");

                    b.HasIndex("SponsorId");

                    b.ToTable("CommissionLinks", t =>
                        {
                            t.HasCheckConstraint("CK_CommissionLinks_NoSelfSponsor", "[DownlineId] <> [SponsorId]");
                        });
                });

            modelBuilder.Entity("LeadManagementPortal.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ConversionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConvertedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DaysToConvert")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LeadCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OriginalLeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SalesGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SalesRepId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversionDate");

                    b.HasIndex("ConvertedById");

                    b.HasIndex("Email");

                    b.HasIndex("Phone");

                    b.HasIndex("SalesGroupId");

                    b.HasIndex("SalesRepId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CustomerAudit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetCustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Term")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("TargetCustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerAudits");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ImportProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UploadedById")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ImportProfileId");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedById");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ImportProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnMappingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "IsActive");

                    b.ToTable("ImportProfiles");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ImportRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessAccountExternalKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BusinessAccountId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessAccountName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreditedRepId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalRowId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<string>("MappedPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SaleEventId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedAgreementId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAccountId");

                    b.HasIndex("CreditedRepId");

                    b.HasIndex("SaleEventId");

                    b.HasIndex("SelectedAgreementId");

                    b.HasIndex("Status");

                    b.HasIndex("ImportBatchId", "RowNumber");

                    b.ToTable("ImportRows");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.Lead", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssignedToId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConvertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtensionGrantedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExtensionGrantedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExtended")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastContactDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SalesGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SalesOrgId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Email");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("Phone");

                    b.HasIndex("SalesGroupId");

                    b.HasIndex("SalesOrgId");

                    b.HasIndex("Status");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.LeadAudit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Details")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("LeadAudits");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.LeadDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadDocuments");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.LeadExtensionAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysAdded")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrantedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NewExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PreviousExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GrantedAtUtc");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadExtensionAudits");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.LeadFollowUpTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadFollowUpTasks");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("Role");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.PayoutBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PaidAtUtc");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("PayoutBatches");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.PayoutEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BeneficiaryId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CommissionAdjustmentId")
                        .HasColumnType("int");

                    b.Property<int?>("CommissionLedgerEntryId")
                        .HasColumnType("int");

                    b.Property<int>("PayoutBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("CommissionAdjustmentId");

                    b.HasIndex("CommissionLedgerEntryId");

                    b.HasIndex("PayoutBatchId");

                    b.ToTable("PayoutEntries", t =>
                        {
                            t.HasCheckConstraint("CK_PayoutEntries_SourceSelection", "(([CommissionLedgerEntryId] IS NOT NULL AND [CommissionAdjustmentId] IS NULL) OR ([CommissionLedgerEntryId] IS NULL AND [CommissionAdjustmentId] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("LeadManagementPortal.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SaleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessAccountId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreditedRepId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalRowId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PostedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessAccountId");

                    b.HasIndex("CreditedRepId");

                    b.HasIndex("PostedById");

                    b.HasIndex("SaleDate");

                    b.ToTable("SaleEvents");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SaleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("CostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImportBatchId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("SaleDate");

                    b.ToTable("SaleRecords");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SalesGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupAdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GroupAdminId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SalesGroups");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SalesOrg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SalesGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("SalesGroupId");

                    b.ToTable("SalesOrgs");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoolingPeriodDays")
                        .HasColumnType("int");

                    b.Property<int>("LeadExtensionDays")
                        .HasColumnType("int");

                    b.Property<int>("LeadInitialExpiryDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoolingPeriodDays = 15,
                            LeadExtensionDays = 5,
                            LeadInitialExpiryDays = 15
                        });
                });

            modelBuilder.Entity("LeadProducts", b =>
                {
                    b.Property<string>("LeadId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LeadId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("LeadProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ApplicationUser", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.SalesGroup", "SalesGroup")
                        .WithMany("SalesReps")
                        .HasForeignKey("SalesGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.SalesOrg", "SalesOrg")
                        .WithMany("SalesReps")
                        .HasForeignKey("SalesOrgId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SalesGroup");

                    b.Navigation("SalesOrg");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.BusinessAccountProductPrice", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.BusinessAccount", "BusinessAccount")
                        .WithMany("ProductPrices")
                        .HasForeignKey("BusinessAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessAccount");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAdjustment", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAgreement", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.BusinessAccount", "BusinessAccount")
                        .WithMany("Agreements")
                        .HasForeignKey("BusinessAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessAccount");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAgreementRecipient", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.CommissionAgreementRecipient", "BasisRecipient")
                        .WithMany("DownstreamRecipients")
                        .HasForeignKey("BasisRecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.CommissionAgreement", "CommissionAgreement")
                        .WithMany("Recipients")
                        .HasForeignKey("CommissionAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasisRecipient");

                    b.Navigation("Beneficiary");

                    b.Navigation("CommissionAgreement");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionDeal", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("CommissionDeal")
                        .HasForeignKey("LeadManagementPortal.Models.CommissionDeal", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionLedger", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "Beneficiary")
                        .WithMany("CommissionLedgers")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.SaleRecord", "SaleRecord")
                        .WithMany("CommissionLedgers")
                        .HasForeignKey("SaleRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("SaleRecord");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionLedgerEntry", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.CommissionAgreement", "CommissionAgreement")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("CommissionAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.CommissionAgreementRecipient", "CommissionAgreementRecipient")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("CommissionAgreementRecipientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.SaleEvent", "SaleEvent")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("SaleEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("CommissionAgreement");

                    b.Navigation("CommissionAgreementRecipient");

                    b.Navigation("SaleEvent");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionLink", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "Downline")
                        .WithOne("SponsorLink")
                        .HasForeignKey("LeadManagementPortal.Models.CommissionLink", "DownlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "Sponsor")
                        .WithMany("SponsoredDownlines")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Downline");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.Customer", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "ConvertedBy")
                        .WithMany()
                        .HasForeignKey("ConvertedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.SalesGroup", "SalesGroup")
                        .WithMany()
                        .HasForeignKey("SalesGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "SalesRep")
                        .WithMany()
                        .HasForeignKey("SalesRepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConvertedBy");

                    b.Navigation("SalesGroup");

                    b.Navigation("SalesRep");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CustomerAudit", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("TargetCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ImportBatch", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ImportProfile", "ImportProfile")
                        .WithMany("ImportBatches")
                        .HasForeignKey("ImportProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportProfile");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ImportRow", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.BusinessAccount", "BusinessAccount")
                        .WithMany()
                        .HasForeignKey("BusinessAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "CreditedRep")
                        .WithMany()
                        .HasForeignKey("CreditedRepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.ImportBatch", "ImportBatch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.SaleEvent", "SaleEvent")
                        .WithMany()
                        .HasForeignKey("SaleEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.CommissionAgreement", "SelectedAgreement")
                        .WithMany()
                        .HasForeignKey("SelectedAgreementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BusinessAccount");

                    b.Navigation("CreditedRep");

                    b.Navigation("ImportBatch");

                    b.Navigation("SaleEvent");

                    b.Navigation("SelectedAgreement");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.Lead", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "AssignedTo")
                        .WithMany("Leads")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.SalesGroup", "SalesGroup")
                        .WithMany("Leads")
                        .HasForeignKey("SalesGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.SalesOrg", "SalesOrg")
                        .WithMany()
                        .HasForeignKey("SalesOrgId");

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("SalesGroup");

                    b.Navigation("SalesOrg");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.LeadAudit", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LeadManagementPortal.Models.LeadDocument", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.Lead", null)
                        .WithMany("Documents")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeadManagementPortal.Models.LeadExtensionAudit", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.LeadFollowUpTask", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.Lead", "Lead")
                        .WithMany("FollowUpTasks")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.Notification", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.PayoutBatch", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.PayoutEntry", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.CommissionAdjustment", "CommissionAdjustment")
                        .WithMany("PayoutEntries")
                        .HasForeignKey("CommissionAdjustmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeadManagementPortal.Models.CommissionLedgerEntry", "CommissionLedgerEntry")
                        .WithMany("PayoutEntries")
                        .HasForeignKey("CommissionLedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeadManagementPortal.Models.PayoutBatch", "PayoutBatch")
                        .WithMany("Entries")
                        .HasForeignKey("PayoutBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("CommissionAdjustment");

                    b.Navigation("CommissionLedgerEntry");

                    b.Navigation("PayoutBatch");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SaleEvent", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.BusinessAccount", "BusinessAccount")
                        .WithMany("SaleEvents")
                        .HasForeignKey("BusinessAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "CreditedRep")
                        .WithMany()
                        .HasForeignKey("CreditedRepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessAccount");

                    b.Navigation("CreditedRep");

                    b.Navigation("PostedBy");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SaleRecord", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "Account")
                        .WithMany("SaleRecords")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SalesGroup", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", "GroupAdmin")
                        .WithMany()
                        .HasForeignKey("GroupAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GroupAdmin");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SalesOrg", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.SalesGroup", "SalesGroup")
                        .WithMany("SalesOrgs")
                        .HasForeignKey("SalesGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesGroup");
                });

            modelBuilder.Entity("LeadProducts", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LeadManagementPortal.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ApplicationUser", b =>
                {
                    b.Navigation("CommissionDeal");

                    b.Navigation("CommissionLedgers");

                    b.Navigation("Leads");

                    b.Navigation("SaleRecords");

                    b.Navigation("SponsorLink");

                    b.Navigation("SponsoredDownlines");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.BusinessAccount", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("ProductPrices");

                    b.Navigation("SaleEvents");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAdjustment", b =>
                {
                    b.Navigation("PayoutEntries");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAgreement", b =>
                {
                    b.Navigation("LedgerEntries");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionAgreementRecipient", b =>
                {
                    b.Navigation("DownstreamRecipients");

                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.CommissionLedgerEntry", b =>
                {
                    b.Navigation("PayoutEntries");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.ImportProfile", b =>
                {
                    b.Navigation("ImportBatches");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.Lead", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("FollowUpTasks");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.PayoutBatch", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SaleEvent", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SaleRecord", b =>
                {
                    b.Navigation("CommissionLedgers");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SalesGroup", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("SalesOrgs");

                    b.Navigation("SalesReps");
                });

            modelBuilder.Entity("LeadManagementPortal.Models.SalesOrg", b =>
                {
                    b.Navigation("SalesReps");
                });
#pragma warning restore 612, 618
        }
    }
}
